/**:
  ros__parameters:
    odom_freq: 20
    transform_tolerance: 0.2
    global_frame_id: "map"
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    footprint_frame_id: "base_link"
    laser_min_range: 1.0
    laser_max_range: 100000000.0
    scan_increment: 1
    initial_pose_x: 0.0
    initial_pose_y: 0.0
    initial_pose_a: 0.0
    num_particles: 500
    alpha_threshold: 1.2
    expansion_radius_position: 0.2  # デフォルト: 0.1 → 増やして位置情報の広がりを強調
    expansion_radius_orientation: 0.5  # デフォルト: 0.2 → 増やす
    extraction_rate: 0.1
    range_threshold: 0.3
    sensor_reset: false
    odom_fw_dev_per_fw: 0.3  # デフォルト: 0.19 → 増やして信頼性を下げる
    odom_fw_dev_per_rot: 0.0005  # デフォルト: 0.0001 → 増やして信頼性を下げる
    odom_rot_dev_per_fw: 0.2  # デフォルト: 0.13 → 増やす
    odom_rot_dev_per_rot: 0.5  # デフォルト: 0.2 → 増やす
    laser_likelihood_max_dist: 12.0
